/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.articulo;

import controlador.ArticuloControlador;
import javax.swing.JOptionPane;
import modelo.Articulo;
import vista.HelperVista;

/**
 *
 * @author departamento
 */
public class LibroJPanel extends javax.swing.JPanel {

    ArticuloControlador ac;
    Articulo art;
    /**
     * Creates new form LibroJPanel
     */
    public LibroJPanel() {
        initComponents();
    }

    LibroJPanel(Articulo art, ArticuloControlador control) {
        initComponents();
        this.ac = control;
        this.art = art;
        jltitulo.setText(art.getNombre_artic());
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtEscritor = new javax.swing.JTextField();
        jtNumeroPaginas = new javax.swing.JTextField();
        jcbSaga = new javax.swing.JCheckBox();
        jBGuardar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jltitulo = new javax.swing.JLabel();

        jLabel1.setText("escritor");

        jLabel2.setText("número de páginas");

        jcbSaga.setText("  Saga");

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jltitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jltitulo.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jltitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBGuardar)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbSaga)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtEscritor)
                        .addComponent(jtNumeroPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jBCancelar)))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jltitulo)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtEscritor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtNumeroPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jcbSaga)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCancelar)
                    .addComponent(jBGuardar))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        destruir();
        
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        if (jtEscritor.getText().isEmpty()||jtNumeroPaginas.getText().isEmpty()||!HelperVista.isNumber(jtNumeroPaginas.getText())) {
            JOptionPane.showMessageDialog(null,"Se tienen que rellenar todos los campos");  
        }else{
            if (ac.nuevoLibro(jtEscritor.getText(),Integer.parseInt(jtNumeroPaginas.getText()), jcbSaga.isSelected(), art)) {
                JOptionPane.showMessageDialog(null,"Libro creado con exito");  
                destruir();
            }else{
                JOptionPane.showMessageDialog(null,"Error al crear el libro");  
            }
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void destruir(){
        MenuArticulo ma =  (MenuArticulo) this.getTopLevelAncestor();
        ma.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox jcbSaga;
    private javax.swing.JLabel jltitulo;
    private javax.swing.JTextField jtEscritor;
    private javax.swing.JTextField jtNumeroPaginas;
    // End of variables declaration//GEN-END:variables
}
